[tool.poetry]
name = "goit-web-01"
version = "0.1.0"
description = ""
authors = ["Alex <oleksii.uzhva.pz.2021@lpnu.ua>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
